-- Create Departments table
create table public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  general_pin text not null unique, -- The general PIN for the department
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Employees table
create table public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  pin text not null unique, -- Unique PIN for the employee
  department_id bigint references public.departments(id) on delete set null,
  role text default 'user', -- 'user' or 'admin'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Seed Data
-- 1. Departments
insert into public.departments (name, general_pin)
values 
  ('Zamówienia', '4321'),
  ('Produkcja', '5555'),
  ('Administracja', '9999');

-- 2. Employees
-- Jan Kowalski (Pin: 1234) in Zamówienia (which has pin 4321)
insert into public.employees (name, pin, department_id, role)
values 
  ('Jan Kowalski', '1234', (select id from public.departments where name = 'Zamówienia'), 'user'),
  ('Anna Nowak', '1111', (select id from public.departments where name = 'Produkcja'), 'user'),
  ('Admin System', '0000', (select id from public.departments where name = 'Administracja'), 'admin');

-- Enable Row Level Security (RLS)
alter table public.departments enable row level security;
alter table public.employees enable row level security;

-- Policies (Simple public read for this demo context, strictly speaking we'd want more security in prod)
-- Allowing public read to validate PINs via client-side query for this specific architecture request
-- Ideally this is done via an Edge Function to keep PINs hidden, but for "SQL dump" request:
create policy "Allow public read access" on public.departments for select using (true);
create policy "Allow public read access" on public.employees for select using (true);
