-- Create Visit Purposes table
create table public.visit_purposes (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Create Badges table
create table public.badges (
  id bigint generated by default as identity primary key,
  badge_number text not null unique,
  is_active boolean default true -- To soft delete/disable badges if needed
);

-- Create Visits table
create table public.visits (
  id bigint generated by default as identity primary key,
  entry_time timestamp with time zone default timezone('utc'::text, now()) not null,
  exit_time timestamp with time zone,
  employee_id bigint references public.employees(id) not null,
  purpose_id bigint references public.visit_purposes(id) not null,
  badge_id bigint references public.badges(id) not null,
  visitor_name text not null,
  notes text,
  signature text, -- Storing base64 string of the signature
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add Seed Data for Purposes
insert into public.visit_purposes (name)
values 
  ('Spotkanie biznesowe'),
  ('Serwis / Naprawa'),
  ('Audyt / Kontrola organu'),
  ('Dostawa'),
  ('Rekrutacja'),
  ('Szkolenie'),
  ('Inne');

-- Add Seed Data for Badges
insert into public.badges (badge_number)
values 
  ('G001'), ('G002'), ('G003'), ('G004'), ('G005'),
  ('G006'), ('G007'), ('G008'), ('G009'), ('G010');

-- Enable RLS
alter table public.visit_purposes enable row level security;
alter table public.badges enable row level security;
alter table public.visits enable row level security;

-- Policies (Public read/write for kiosk demo)
create policy "Allow public read access" on public.visit_purposes for select using (true);
create policy "Allow public read access" on public.badges for select using (true);
create policy "Allow public read access" on public.visits for select using (true);
create policy "Allow public insert access" on public.visits for insert with check (true);
create policy "Allow public update access" on public.visits for update using (true);
